# Generated by Django 2.2.7 on 2020-03-26 07:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=33)),
                ('deaths', models.CharField(max_length=33)),
                ('recovered', models.CharField(max_length=33)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Total(Country)',
                'db_table': 'casescountry',
            },
        ),
        migrations.CreateModel(
            name='CaseswithDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.CharField(max_length=33)),
                ('deaths', models.CharField(max_length=33)),
                ('recovered', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name_plural': 'Cases as a Date',
                'db_table': 'casesdate',
            },
        ),
        migrations.CreateModel(
            name='WorldWide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=33)),
                ('deaths', models.CharField(max_length=33)),
                ('recovered', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name_plural': 'WorldWide',
                'db_table': 'worldwide',
            },
        ),
    ]
